apiVersion: eks.aws.upbound.io/v1beta1
kind: Addon
metadata:
  
  name: aws-ebs-csi-driver
spec:
  forProvider:
    addonName: aws-ebs-csi-driver
    addonVersion: v1.23.0-eksbuild.1
    region: us-east-1
    serviceAccountRoleArn: arn:aws:iam::696776820132:role/eks-ebs-csi-driver
    clusterNameRef:
      name: crossplane-eks-cluster