---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: eks-ebs-csi-driver
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Principal": {
              "Federated": "arn:aws:iam::696776820132:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/F5C37859A96AAF0A0518BBB857908EB4"
            },
            "Condition": {
              "StringEquals": {
                "oidc.eks.us-east-1.amazonaws.com/id/F5C37859A96AAF0A0518BBB857908EB4:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
                 
              }
            }
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-ebs-csi-driver-amazon-ebs-csi-driver-policy
spec:
  forProvider:
    role: eks-ebs-csi-driver
    policyArn: arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
    