apiVersion: iam.aws.upbound.io/v1beta1
kind: OpenIDConnectProvider
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: This resource needs valid OpenID Connect id and url.
  name: crossplane-openid
spec:
  forProvider:
    clientIdList:
      - sts.amazonaws.com
    thumbprintList:
      - 9e99a48a9960b14926bb7f3b02e22da2b0ab7280
    url: https://oidc.eks.us-east-1.amazonaws.com/id/F5C37859A96AAF0A0518BBB857908EB4
         