---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: cluster-autoscaler
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Principal": {
              "Federated": "arn:aws:iam::696776820132:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/F5C37859A96AAF0A0518BBB857908EB4"
            },
            "Condition": {
              "StringEquals": {
                "oidc.eks.us-east-1.amazonaws.com/id/F5C37859A96AAF0A0518BBB857908EB4:sub": "system:serviceaccount:kube-system:cluster-autoscaler"
              }
            }
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: cluster-autoscaler
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "autoscaling:DescribeAutoScalingGroups",
              "autoscaling:DescribeAutoScalingInstances",
              "autoscaling:DescribeLaunchConfigurations",
              "autoscaling:DescribeScalingActivities",
              "ec2:DescribeInstanceTypes",
              "ec2:DescribeLaunchTemplateVersions"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "autoscaling:SetDesiredCapacity",
              "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: cluster-autoscaler
spec:
  forProvider:
    role: cluster-autoscaler
    policyArnRef:
      name: cluster-autoscaler