apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: crossplane-eks-cluster-role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Effect": "Allow"
            
          }
        ]

      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: crossplane-eks-cluster-role-policy-attachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    role: crossplane-eks-cluster-role