apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: crossplane-vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: us-east-1
    enableDnsHostnames: true
    enableDnsSupport: true
    tags:
      Name: crossplane
  